version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  ping:
    lang: dockerfile
    handler: ./ping
    image: ttl.sh/welteki/ping:0.0.2

  ndjson:
    lang: golang-middleware
    handler: ./ndjson
    image: ttl.sh/welteki/ndjson:0.0.1
    environment:
      exec_timeout: 10m
      write_timeout: 10m
      read_timeout: 10m

  callback-counter:
    lang: golang-middleware
    handler: ./callback-counter
    image: ttl.sh/welteki/callback-counter:0.0.1
    labels:
      com.openfaas.scale.min: "1"
      com.openfaas.scale.max: "1"

  async-load:
    lang: golang-middleware
    handler: ./async-load
    image: ttl.sh/welteki/async-load:0.0.10
    labels:
      com.openfaas.scale.min: "1"
      com.openfaas.scale.max: "1"
    environment:
      OPENFAAS_URL: http://gateway.openfaas:8080
      # OPENFAAS_URL: https://slicer-gw.exit.welteki.dev

  transient-chaos:
    lang: golang-middleware
    handler: ./transient-chaos
    image: ttl.sh/welteki/transient-chaos:0.0.1
    labels:
      com.openfaas.scale.min: "1"
      com.openfaas.scale.max: "1"

  variable-inflight:
    lang: golang-middleware
    handler: ./variable-inflight
    image: ttl.sh/welteki/variable-inflight:0.0.4
    annotations:
      com.openfaas.ready.http.path: "/_/ready"
    labels:
      com.openfaas.scale.min: "1"
      com.openfaas.scale.max: "1"
    environment:
      exec_timeout: 1h
      write_timeout: 1h1m
      read_timeout: 1h1m

  overload-simulator:
    lang: golang-middleware
    handler: ./overload-simulator
    image: ttl.sh/welteki/overload-simulator:0.0.1
    annotations:
      com.openfaas.ready.http.path: "/ready"
    labels:
      com.openfaas.scale.min: "1"
      com.openfaas.scale.max: "1"
    environment:
      inflight_threshold: "5"
      failure_mode: "constant"
      sleep_duration: "100ms"
      use_ready_endpoint: "true"
